---
- name: toto.txt
  hosts: docusaurus
  remote_user: root

  roles:
  - apache

  tasks:
  - name: create empty toto.txt files
    ansible.builtin.file:
      path: /etc/toto32.txt
      state: touch