---
- name: toto.txt
  hosts: jolly_lamarr
  remote_user: root

  roles:
  - apache2

  tasks:
  - name: create empty toto.txt files
    ansible.builtin.file:
      path: /etc/toto32.txt
      state: touch