---
- name: toto.txt
  hosts: vigilant_banzai
  remote_user: root

  roles:
  - apache2
# - mariadb

  tasks:
  - name: create empty toto.txt files
    ansible.builtin.file:
      path: /etc/toto10.txt
      state: touch


