name: Ansible configuration conteneur
on: [workflow_dispatch]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Donne la date pour test 1
      run: date

    - name: Copie de etc ansible l
      run: cp -r etc /home/benjamin/ansible2/

    - name: Copie de playbook ansible
      run: cp -r playbook /home/benjamin/ansible2/

    - name: Execution de la configuration de yml Ansible
      run: ansible-playbook /home/benjamin/ansible2/playbook/recette.yml -v

    - name: Execution de la configuration de yml Ansible
      run: ansible-playbook /home/benjamin/ansible2/playbook/recette2.yml -v
