name: configuration conteneur
on: [push, workflow_dispatch]

jobs:

  deploy1:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: donne la date pour test
      run: date

    - name: test
      run: ls c:\