name: configuration conteneur
on: [push]

jobs:

  deploy1:

    runs-on: self-hosted

    steps:
    - name: Checkout h
      uses: actions/checkout@v4 
    
    - name: donne la date pour test
      run: date

    - name: test
      run: ls c:\